# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://mldizd.github.io/
title: Milad Izadi
email: mizad001@ucr.edu
author: Milad Izadi
description: "Milad's Personal Page"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
# Build sitemap
plugins:
  - jekyll-sitemap

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - icon: github
    title: github
    url: https://mldizd.github.io/ 
  - icon: envelope-o
    title: email
    url: mailto:NyName@gmail.com
  - icon: linkedin
    title: linkedin
    url: https://www.linkedin.com/in/milad-izadi/
#  - icon: file-pdf-o
#    title: CV
#    url: img/MyCV.pdf
  - icon: twitter
    title: twitter
    url: https://twitter.com/MyName
  - icon: GoogleScholar
    title: GoogleScholar
    url: https://scholar.google.com/citations?user=DdoGj5cAAAAJ&hl=en
    

